// Generated by CoffeeScript 1.6.3
(function() {
  var DashingClient, exports, lodash, rest;

  rest = require('restler');

  lodash = require('lodash');

  DashingClient = (function() {
    function DashingClient(dashingBaseUri, apiKey, options) {
      this.dashingBaseUri = dashingBaseUri;
      this.apiKey = apiKey;
      this.options = options;
    }

    DashingClient.prototype.send = function(widgetId, data) {
      data = lodash.extend({}, data, {
        auth_token: this.apiKey
      });
      return rest.postJson("" + this.dashingBaseUri + "/widgets/" + widgetId, data, this.options);
    };

    DashingClient.prototype.toString = function() {
      return "DashingClient for " + this.dashingBaseUri;
    };

    return DashingClient;

  })();

  module.exports = exports = DashingClient;

}).call(this);
